"""empty message

Revision ID: 130bb420540a
Revises: aa9a3f114a27
Create Date: 2024-03-23 20:54:09.959818

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "130bb420540a"
down_revision = "aa9a3f114a27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "json_schema", "pipeline_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        "json_schema_pipeline_id_type_key", "json_schema", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "json_schema_pipeline_id_type_key",
        "json_schema",
        ["pipeline_id", "type"],
    )
    op.alter_column(
        "json_schema", "pipeline_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
