"""empty message

Revision ID: aa9a3f114a27
Revises: dfc2a414b9ce
Create Date: 2024-03-23 20:27:49.358839

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa9a3f114a27"
down_revision = "dfc2a414b9ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "json_schema", ["pipeline_id", "type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "json_schema", type_="unique")
    # ### end Alembic commands ###
