"""empty message

Revision ID: 11a96aaf2997
Revises: e9d5a4cf60c4
Create Date: 2024-03-23 17:33:44.574428

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "11a96aaf2997"
down_revision = "e9d5a4cf60c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "pipeline", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pipeline", type_="unique")
    # ### end Alembic commands ###
