"""empty message

Revision ID: 7e2eb314ce0b
Revises: 1fe1d3185682
Create Date: 2024-03-24 01:31:21.363138

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e2eb314ce0b"
down_revision = "1fe1d3185682"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pipeline_slug_key", "pipeline", type_="unique")
    op.drop_column("pipeline", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pipeline",
        sa.Column("slug", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("pipeline_slug_key", "pipeline", ["slug"])
    # ### end Alembic commands ###
