"""empty message

Revision ID: 4c30b526b026
Revises: 11a96aaf2997
Create Date: 2024-03-23 19:02:31.644205

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c30b526b026"
down_revision = "11a96aaf2997"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jsonschema",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("input", "output", name="jsonschematypeenum"),
            nullable=False,
        ),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jsonschema")
    # ### end Alembic commands ###
